### ISSUE TITLE
Balance check at end of exodus test assumes empty account

### ISSUE THREAD

**Issue by ColonelJ** [matter-labs-archive/atomic-swaps#4]
https://github.com/matter-labs/atomic-swaps/blob/a7c6ee201ae5994f7c987ed10c2d6293ed894145/test/flow.test.ts#L284

It seems like this should check the balance before the `clientWithdraw` and check how much it has increased, instead of assuming that the account was empty beforehand.

**Comment by ly0va** [comment]
Fixed
